**Rupa Kodali (S02057353)**

1) Define the following metrics and perform the following operations
I)Write a Python program using Python Lists
II)Write a Python program and NumPy

Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
[1.1254  2.8956,  5.9187]].

In [1]:
import cProfile

# Define matrices
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# Function to perform matrix addition
def matrix_addition(A, B, C):
    return [[A[i][j] + B[i][j] + C[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# Perform the operation and print the result
result_list = matrix_addition(A, B, C)
print("Matrix Addition using Python Lists:")
for row in result_list:
    print(row)

# Profile the matrix addition
cProfile.run('matrix_addition(A, B, C)')


Matrix Addition using Python Lists:
[10.0304, 9.543000000000001, 9.4831]
[6.9954, 10.4685, 11.143699999999999]
[3.3475, 7.1346, 16.9508]
         8 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 1969095039.py:9(matrix_addition)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        4    0.000    0.000    0.000    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [2]:
import numpy as np
import cProfile

# Define matrices using NumPy arrays
A_np = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
B_np = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
C_np = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

# Function to perform matrix addition using NumPy
def matrix_addition_numpy(A, B, C):
    return A + B + C

# Perform the operation and print the result
result_numpy = matrix_addition_numpy(A_np, B_np, C_np)
print("Matrix Addition using NumPy:")
print(result_numpy)

# Profile the matrix addition using NumPy
cProfile.run('matrix_addition_numpy(A_np, B_np, C_np)')


Matrix Addition using NumPy:
[[10.0304  9.543   9.4831]
 [ 6.9954 10.4685 11.1437]
 [ 3.3475  7.1346 16.9508]]
         4 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 1360275695.py:10(matrix_addition_numpy)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




2) Write a Python Program and perform the following operations ?

Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}


In [3]:
lst = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

Iterate using a for loop


In [4]:
def iterate_for_loop(lst):
    for item in lst:
        print(item)

print("\nIterate using a for loop:")
cProfile.run('iterate_for_loop(lst)')


Iterate using a for loop:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456
         234 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 1282566853.py:1(iterate_for_loop)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
       20    0.000    0.000    0.000    0.000 iostream.py:505(parent_header)
       20    0.000    0.000    0.000    0.000 iostream.py:550(_is_master_process)
       20    0.000    0.000    0.000    0.000 iostream.py:577(_schedule_flush)
       20    0.000    0.000    0.000    0.000 iostream.py:655(write)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
       20    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
       20    0.000    0.000    0.000    0.000 {built-in method builtins.len}
       10    0.000    0.000    0.000    0.000 {built-in method builtins.print}
    

Iterate using for loop and range

In [5]:
def iterate_for_loop_range(lst):
    for i in range(len(lst)):
        print(lst[i])

print("\nIterate using for loop and range:")
cProfile.run('iterate_for_loop_range(lst)')


Iterate using for loop and range:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456
         235 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 4259948634.py:1(iterate_for_loop_range)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
       20    0.000    0.000    0.000    0.000 iostream.py:505(parent_header)
       20    0.000    0.000    0.000    0.000 iostream.py:550(_is_master_process)
       20    0.000    0.000    0.000    0.000 iostream.py:577(_schedule_flush)
       20    0.000    0.000    0.000    0.000 iostream.py:655(write)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
       20    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
       21    0.000    0.000    0.000    0.000 {built-in method builtins.len}
       10    0.000    0.000    0.000    0.000 {built-in method builti

List Comprehension

In [6]:
def list_comprehension(lst):
    result = [x**2 for x in lst]
    print(result)

print("\nList Comprehension:")
cProfile.run('list_comprehension(lst)')


List Comprehension:
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]
         27 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 1432325590.py:1(list_comprehension)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        2    0.000    0.000    0.000    0.000 iostream.py:505(parent_header)
        2    0.000    0.000    0.000    0.000 iostream.py:550(_is_master_process)
        2    0.000    0.000    0.000    0.000 iostream.py:577(_schedule_flush)
        2    0.000    0.000    0.000    0.000 iostream.py:655(write)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        2    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
        2    0.000    0.000    0.000    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0

Enumerate

In [7]:
def use_enumerate(lst):
    for index, value in enumerate(lst):
        print(f"Index: {index}, Value: {value}")

print("\nUsing enumerate:")
cProfile.run('use_enumerate(lst)')


Using enumerate:
Index: 0, Value: 1225
Index: 1, Value: 4986
Index: 2, Value: 6789
Index: 3, Value: 7890
Index: 4, Value: 2345
Index: 5, Value: 6783
Index: 6, Value: 987
Index: 7, Value: 1234
Index: 8, Value: 8765
Index: 9, Value: 3456
         234 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 686250436.py:1(use_enumerate)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
       20    0.000    0.000    0.000    0.000 iostream.py:505(parent_header)
       20    0.000    0.000    0.000    0.000 iostream.py:550(_is_master_process)
       20    0.000    0.000    0.000    0.000 iostream.py:577(_schedule_flush)
       20    0.000    0.000    0.000    0.000 iostream.py:655(write)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
       20    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
   

Iter function and next function


In [8]:
def use_iter_next(lst):
    iterator = iter(lst)
    try:
        while True:
            print(next(iterator))
    except StopIteration:
        pass

print("\nUsing iter and next functions:")
cProfile.run('use_iter_next(lst)')


Using iter and next functions:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456
         246 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 3435334907.py:1(use_iter_next)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
       20    0.000    0.000    0.000    0.000 iostream.py:505(parent_header)
       20    0.000    0.000    0.000    0.000 iostream.py:550(_is_master_process)
       20    0.000    0.000    0.000    0.000 iostream.py:577(_schedule_flush)
       20    0.000    0.000    0.000    0.000 iostream.py:655(write)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
       20    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
        1    0.000    0.000    0.000    0.000 {built-in method builtins.iter}
       20    0.000    0.000    0.000    0.000 {built-in method builtins.len}
   

Map function

In [9]:
def use_map(lst):
    result = list(map(lambda x: x**2, lst))
    print(result)

print("\nUsing map function:")
cProfile.run('use_map(lst)')


Using map function:
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]
         37 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 2624965587.py:1(use_map)
       10    0.000    0.000    0.000    0.000 2624965587.py:2(<lambda>)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        2    0.000    0.000    0.000    0.000 iostream.py:505(parent_header)
        2    0.000    0.000    0.000    0.000 iostream.py:550(_is_master_process)
        2    0.000    0.000    0.000    0.000 iostream.py:577(_schedule_flush)
        2    0.000    0.000    0.000    0.000 iostream.py:655(write)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        2    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
        2    0.000    0.000    0.000    0.000 {built-in m

Using zip

In [10]:
def use_zip(lst):
    lst2 = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
    for item1, item2 in zip(lst, lst2):
        print(f"{item1} -> {item2}")

print("\nUsing zip:")
cProfile.run('use_zip(lst)')


Using zip:
1225 -> 5
4986 -> 6
6789 -> 7
7890 -> 8
2345 -> 9
6783 -> 10
987 -> 11
1234 -> 12
8765 -> 13
3456 -> 14
         234 function calls in 0.001 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 810646341.py:1(use_zip)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
       20    0.000    0.000    0.000    0.000 iostream.py:505(parent_header)
       20    0.000    0.000    0.000    0.000 iostream.py:550(_is_master_process)
       20    0.000    0.000    0.000    0.000 iostream.py:577(_schedule_flush)
       20    0.000    0.000    0.000    0.000 iostream.py:655(write)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
       20    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
       20    0.000    0.000    0.000    0.000 {built-in method builtins.len}
       10    0.000    0.000    0.000    0.000 {built-

Using NumPy Module

In [11]:
def use_numpy(lst):
    np_lst = np.array(lst)
    result = np_lst * 2
    print(result)

print("\nUsing NumPy:")
cProfile.run('use_numpy(lst)')


Using NumPy:
[ 2450  9972 13578 15780  4690 13566  1974  2468 17530  6912]
         195 function calls (185 primitive calls) in 0.001 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 1527138106.py:1(use_numpy)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 arrayprint.py:1265(__init__)
       10    0.000    0.000    0.000    0.000 arrayprint.py:1280(__call__)
        1    0.000    0.000    0.000    0.000 arrayprint.py:1666(_array_str_implementation)
        1    0.000    0.000    0.000    0.000 arrayprint.py:427(_get_formatdict)
        1    0.000    0.000    0.000    0.000 arrayprint.py:435(<lambda>)
        1    0.000    0.000    0.000    0.000 arrayprint.py:477(_get_format_function)
        1    0.000    0.000    0.000    0.000 arrayprint.py:50(_make_options_dict)
        1    0.000    0.000    0.000    0.000 ar

3) For a List A, B, C, D, E write a python program to compute all the combinations and permutations 

In [12]:
def get_permutations(lst):
    if len(lst) == 0:
        return []
    if len(lst) == 1:
        return [lst]
    
    perms = []
    for i in range(len(lst)):
        current = lst[i]
        remaining_lst = lst[:i] + lst[i+1:]
        for p in get_permutations(remaining_lst):
            perms.append([current] + p)
    return perms

lst_letters = ['A', 'B', 'C', 'D', 'E']

# Compute and print the permutations
print("\nPermutations:")
permutations = get_permutations(lst_letters)
for perm in permutations:
    print(perm)

# Profile the permutations function
cProfile.run('get_permutations(lst_letters)')


Permutations:
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'E', 'D']
['A', 'B', 'D', 'C', 'E']
['A', 'B', 'D', 'E', 'C']
['A', 'B', 'E', 'C', 'D']
['A', 'B', 'E', 'D', 'C']
['A', 'C', 'B', 'D', 'E']
['A', 'C', 'B', 'E', 'D']
['A', 'C', 'D', 'B', 'E']
['A', 'C', 'D', 'E', 'B']
['A', 'C', 'E', 'B', 'D']
['A', 'C', 'E', 'D', 'B']
['A', 'D', 'B', 'C', 'E']
['A', 'D', 'B', 'E', 'C']
['A', 'D', 'C', 'B', 'E']
['A', 'D', 'C', 'E', 'B']
['A', 'D', 'E', 'B', 'C']
['A', 'D', 'E', 'C', 'B']
['A', 'E', 'B', 'C', 'D']
['A', 'E', 'B', 'D', 'C']
['A', 'E', 'C', 'B', 'D']
['A', 'E', 'C', 'D', 'B']
['A', 'E', 'D', 'B', 'C']
['A', 'E', 'D', 'C', 'B']
['B', 'A', 'C', 'D', 'E']
['B', 'A', 'C', 'E', 'D']
['B', 'A', 'D', 'C', 'E']
['B', 'A', 'D', 'E', 'C']
['B', 'A', 'E', 'C', 'D']
['B', 'A', 'E', 'D', 'C']
['B', 'C', 'A', 'D', 'E']
['B', 'C', 'A', 'E', 'D']
['B', 'C', 'D', 'A', 'E']
['B', 'C', 'D', 'E', 'A']
['B', 'C', 'E', 'A', 'D']
['B', 'C', 'E', 'D', 'A']
['B', 'D', 'A', 'C', 'E']
['B', 'D', 'A', 'E', 'C

In [13]:
def get_combinations(lst, r):
    if r == 0:
        return [[]]
    if len(lst) == 0:
        return []
    
    combs = []
    for i in range(len(lst)):
        current = lst[i]
        remaining_lst = lst[i+1:]
        for c in get_combinations(remaining_lst, r-1):
            combs.append([current] + c)
    
    return combs

# Compute and print the combinations for r=2
print("\nCombinations (r=2):")
combinations = get_combinations(lst_letters, 2)
for comb in combinations:
    print(comb)

# Profile the combinations function (for r=2)
cProfile.run('get_combinations(lst_letters, 2)')


Combinations (r=2):
['A', 'B']
['A', 'C']
['A', 'D']
['A', 'E']
['B', 'C']
['B', 'D']
['B', 'E']
['C', 'D']
['C', 'E']
['D', 'E']
         50 function calls (35 primitive calls) in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     16/1    0.000    0.000    0.000    0.000 3920810396.py:1(get_combinations)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
       11    0.000    0.000    0.000    0.000 {built-in method builtins.len}
       20    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




4) Using the same list use itertools compute permutations and combinations 


In [14]:
import cProfile
from itertools import permutations, combinations

# Compute and print permutations using itertools
print("\nPermutations using itertools:")
perms_itertools = list(permutations(lst_letters))
for perm in perms_itertools:
    print(perm)

# Profile the itertools permutations
cProfile.run("list(permutations(lst_letters))")

# Compute and print combinations using itertools (for r=2)
print("\nCombinations using itertools (r=2):")
combs_itertools = list(combinations(lst_letters, 2))
for comb in combs_itertools:
    print(comb)

# Profile the itertools combinations
cProfile.run("list(combinations(lst_letters, 2))")



Permutations using itertools:
('A', 'B', 'C', 'D', 'E')
('A', 'B', 'C', 'E', 'D')
('A', 'B', 'D', 'C', 'E')
('A', 'B', 'D', 'E', 'C')
('A', 'B', 'E', 'C', 'D')
('A', 'B', 'E', 'D', 'C')
('A', 'C', 'B', 'D', 'E')
('A', 'C', 'B', 'E', 'D')
('A', 'C', 'D', 'B', 'E')
('A', 'C', 'D', 'E', 'B')
('A', 'C', 'E', 'B', 'D')
('A', 'C', 'E', 'D', 'B')
('A', 'D', 'B', 'C', 'E')
('A', 'D', 'B', 'E', 'C')
('A', 'D', 'C', 'B', 'E')
('A', 'D', 'C', 'E', 'B')
('A', 'D', 'E', 'B', 'C')
('A', 'D', 'E', 'C', 'B')
('A', 'E', 'B', 'C', 'D')
('A', 'E', 'B', 'D', 'C')
('A', 'E', 'C', 'B', 'D')
('A', 'E', 'C', 'D', 'B')
('A', 'E', 'D', 'B', 'C')
('A', 'E', 'D', 'C', 'B')
('B', 'A', 'C', 'D', 'E')
('B', 'A', 'C', 'E', 'D')
('B', 'A', 'D', 'C', 'E')
('B', 'A', 'D', 'E', 'C')
('B', 'A', 'E', 'C', 'D')
('B', 'A', 'E', 'D', 'C')
('B', 'C', 'A', 'D', 'E')
('B', 'C', 'A', 'E', 'D')
('B', 'C', 'D', 'A', 'E')
('B', 'C', 'D', 'E', 'A')
('B', 'C', 'E', 'A', 'D')
('B', 'C', 'E', 'D', 'A')
('B', 'D', 'A', 'C', 'E')
('B', '