1) Define the following metrics and perform the following operations
Write a Python program using Python Lists
Write a Python program and NumPy

Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
[1.1254  2.8956,  5.9187]].


In [1]:
# Define matrices using lists
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# matrix addition
result = [[A[i][j] + B[i][j] + C[i][j] for j in range(len(A[0]))] for i in range(len(A))]
print(result)


[[10.0304, 9.543000000000001, 9.4831], [6.9954, 10.4685, 11.143699999999999], [3.3475, 7.1346, 16.9508]]


In [2]:
import numpy as np

# Define matrices using NumPy arrays
A = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
B = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
C = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

# matrix addition
result = A + B + C
print(result)


[[10.0304  9.543   9.4831]
 [ 6.9954 10.4685 11.1437]
 [ 3.3475  7.1346 16.9508]]


2) Write a Python Program and perform the following operations ?

Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}


In [3]:
lst = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

Iterate using a for loop


In [4]:
for item in lst:
    print(item)


1225
4986
6789
7890
2345
6783
987
1234
8765
3456


Iterate using for loop and range

In [5]:
for i in range(len(lst)):
    print(lst[i])


1225
4986
6789
7890
2345
6783
987
1234
8765
3456


List Comprehension

In [6]:
squared_lst = [x**2 for x in lst]
print(squared_lst)

[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]


Enumerate

In [7]:
for index, value in enumerate(lst):
    print(f"Index: {index}, Value: {value}")


Index: 0, Value: 1225
Index: 1, Value: 4986
Index: 2, Value: 6789
Index: 3, Value: 7890
Index: 4, Value: 2345
Index: 5, Value: 6783
Index: 6, Value: 987
Index: 7, Value: 1234
Index: 8, Value: 8765
Index: 9, Value: 3456


Iter function and next function


In [8]:
iterator = iter(lst)
print(next(iterator))
print(next(iterator))


1225
4986


Map function

In [9]:
squared_lst = list(map(lambda x: x**2, lst))
print(squared_lst)


[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]


Using zip

In [10]:
lst2 = [5, 6, 7, 8, 9]
for item1, item2 in zip(lst, lst2):
    print(item1, item2)


1225 5
4986 6
6789 7
7890 8
2345 9


Using NumPy Module

In [11]:
np_lst = np.array(lst)
print(np_lst * 2)

[ 2450  9972 13578 15780  4690 13566  1974  2468 17530  6912]


3) For a List A, B, C, D, E write a python program to compute all the combinations and permutations 

In [12]:
def get_permutations(lst):
    # Base case: if the list is empty, return an empty list
    if len(lst) == 0:
        return []
    
    # Base case: if the list has one element, return a list containing that element
    if len(lst) == 1:
        return [lst]
    
    # Recursive case
    perms = []
    for i in range(len(lst)):
        # Extract the current element
        current = lst[i]
        # Get the remaining elements
        remaining_lst = lst[:i] + lst[i+1:]
        # Generate permutations for the remaining elements
        for p in get_permutations(remaining_lst):
            perms.append([current] + p)
    return perms

lst = ['A', 'B', 'C', 'D', 'E']
permutations = get_permutations(lst)
print(permutations)


[['A', 'B', 'C', 'D', 'E'], ['A', 'B', 'C', 'E', 'D'], ['A', 'B', 'D', 'C', 'E'], ['A', 'B', 'D', 'E', 'C'], ['A', 'B', 'E', 'C', 'D'], ['A', 'B', 'E', 'D', 'C'], ['A', 'C', 'B', 'D', 'E'], ['A', 'C', 'B', 'E', 'D'], ['A', 'C', 'D', 'B', 'E'], ['A', 'C', 'D', 'E', 'B'], ['A', 'C', 'E', 'B', 'D'], ['A', 'C', 'E', 'D', 'B'], ['A', 'D', 'B', 'C', 'E'], ['A', 'D', 'B', 'E', 'C'], ['A', 'D', 'C', 'B', 'E'], ['A', 'D', 'C', 'E', 'B'], ['A', 'D', 'E', 'B', 'C'], ['A', 'D', 'E', 'C', 'B'], ['A', 'E', 'B', 'C', 'D'], ['A', 'E', 'B', 'D', 'C'], ['A', 'E', 'C', 'B', 'D'], ['A', 'E', 'C', 'D', 'B'], ['A', 'E', 'D', 'B', 'C'], ['A', 'E', 'D', 'C', 'B'], ['B', 'A', 'C', 'D', 'E'], ['B', 'A', 'C', 'E', 'D'], ['B', 'A', 'D', 'C', 'E'], ['B', 'A', 'D', 'E', 'C'], ['B', 'A', 'E', 'C', 'D'], ['B', 'A', 'E', 'D', 'C'], ['B', 'C', 'A', 'D', 'E'], ['B', 'C', 'A', 'E', 'D'], ['B', 'C', 'D', 'A', 'E'], ['B', 'C', 'D', 'E', 'A'], ['B', 'C', 'E', 'A', 'D'], ['B', 'C', 'E', 'D', 'A'], ['B', 'D', 'A', 'C', 'E'], 

4) Using the same list use itertools compute permutations and combinations 


In [13]:
from itertools import permutations, combinations

lst = ['A', 'B', 'C', 'D', 'E']

# Permutations
perm = list(permutations(lst))
print(perm)

# Combinations
comb = list(combinations(lst, 2))
print(comb)


[('A', 'B', 'C', 'D', 'E'), ('A', 'B', 'C', 'E', 'D'), ('A', 'B', 'D', 'C', 'E'), ('A', 'B', 'D', 'E', 'C'), ('A', 'B', 'E', 'C', 'D'), ('A', 'B', 'E', 'D', 'C'), ('A', 'C', 'B', 'D', 'E'), ('A', 'C', 'B', 'E', 'D'), ('A', 'C', 'D', 'B', 'E'), ('A', 'C', 'D', 'E', 'B'), ('A', 'C', 'E', 'B', 'D'), ('A', 'C', 'E', 'D', 'B'), ('A', 'D', 'B', 'C', 'E'), ('A', 'D', 'B', 'E', 'C'), ('A', 'D', 'C', 'B', 'E'), ('A', 'D', 'C', 'E', 'B'), ('A', 'D', 'E', 'B', 'C'), ('A', 'D', 'E', 'C', 'B'), ('A', 'E', 'B', 'C', 'D'), ('A', 'E', 'B', 'D', 'C'), ('A', 'E', 'C', 'B', 'D'), ('A', 'E', 'C', 'D', 'B'), ('A', 'E', 'D', 'B', 'C'), ('A', 'E', 'D', 'C', 'B'), ('B', 'A', 'C', 'D', 'E'), ('B', 'A', 'C', 'E', 'D'), ('B', 'A', 'D', 'C', 'E'), ('B', 'A', 'D', 'E', 'C'), ('B', 'A', 'E', 'C', 'D'), ('B', 'A', 'E', 'D', 'C'), ('B', 'C', 'A', 'D', 'E'), ('B', 'C', 'A', 'E', 'D'), ('B', 'C', 'D', 'A', 'E'), ('B', 'C', 'D', 'E', 'A'), ('B', 'C', 'E', 'A', 'D'), ('B', 'C', 'E', 'D', 'A'), ('B', 'D', 'A', 'C', 'E'), 